/home/xzcaplcu/repo/qtrkx-gnn-tracking/test.py:87: RuntimeWarning: invalid value encountered in long_scalars
  precision_5 = tp/(tp+fp) # also named purity
/home/xzcaplcu/repo/qtrkx-gnn-tracking/test.py:95: RuntimeWarning: invalid value encountered in long_scalars
  precision_7 = tp/(tp+fp) # also named purity
/home/xzcaplcu/repo/qtrkx-gnn-tracking/test.py:87: RuntimeWarning: invalid value encountered in long_scalars
  precision_5 = tp/(tp+fp) # also named purity
/home/xzcaplcu/repo/qtrkx-gnn-tracking/test.py:95: RuntimeWarning: invalid value encountered in long_scalars
  precision_7 = tp/(tp+fp) # also named purity
